apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - name: chisel-http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: kafka