apiVersion: v1
kind: BuildConfig
metadata:
  name: zookeeper
  namespace: schaden-zahlung-aete
  labels:
    app: zookeeper
    build: zookeeper
spec:
  runPolicy: Serial
  source:
    type: Git
    git: 
      uri: "https://github.com/MarianneGreten/kafkaimage.git"  
      ref: "master"
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: "ImageStreamTag"
        name: "openjdk18-openshift:latest"
      dockerfilePath: docker/zookeeper/Dockerfile
  triggers:
    - type: ImageChange
      imageChange: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'zookeeper:latest'
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi